---
- name: Download Installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
    dest: "{{ ansible_user_dir }}/lazydocker-installer.sh"

- name: Set executable
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/lazydocker-installer.sh"
    mode: +x

- name: Install
  ansible.builtin.shell:
    cmd: "{{ ansible_user_dir }}/lazydocker-installer.sh"
