---
- name: Create dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/k9s"
    state: directory

- name: Unarchive
  ansible.builtin.unarchive:
    dest: "{{ ansible_user_dir }}/k9s"
    remote_src: true
    src: https://github.com/derailed/k9s/releases/download/v0.26.7/k9s_Linux_x86_64.tar.gz

- name: Install
  ansible.builtin.copy:
    dest: "/usr/bin/k9s"
    src: "{{ ansible_user_dir }}/k9s/k9s"
  become: true

- name: Cleanup
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/k9s"
    state: absent

- name: Directory
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/k9s"
    state: directory

- name: skin.yml
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/k9s/skin.yml"
    src: "skin.yml"
