---
- name: Download Installer
  ansible.builtin.get_url:
    dest: "{{ ansible_user_dir }}/nvm_installer.sh"
    mode: "0755"
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh

- name: Install
  ansible.builtin.shell:
    cmd: "{{ ansible_user_dir }}/nvm_installer.sh"

- name: Cleanup
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/nvm_installer.sh"
    state: absent
