---
- name: Install
  ansible.builtin.package:
    name:
      - git-filter-repo
      - jq
      - open-iscsi
    state: latest
  become: yes

- name: Create bin dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory

- name: Create fonts dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.fonts"
    state: directory

- name: Unarchive Meslo
  ansible.builtin.unarchive:
    dest: "{{ ansible_user_dir }}/.fonts"
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Meslo.zip
    remote_src: true

- name: Unarchive Awesome
  ansible.builtin.unarchive:
    dest: "{{ ansible_user_dir }}/.fonts"
    src: https://use.fontawesome.com/releases/v6.2.1/fontawesome-free-6.2.1-desktop.zip
    remote_src: true

- name: Move Awesome
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.fonts"
    src: "{{ ansible_user_dir }}/.fonts/fontawesome-free-6.2.1-desktop/otfs/"

- name: Cleanup
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.fonts/fontawesome-free-6.2.1-desktop"
    state: absent
    
#- name: Set sudo
#  ansible.builtin.replace:
#    path: "/etc/sudoers"
#    regexp: '\%sudo ALL=\(ALL:ALL\) ALL'
#    replace: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL"
#  become: yes

#- name: Set hosts
#  ansible.builtin.template:
#    dest: "/etc/hosts"
#    src: hosts.j2
#  become: yes

#- name: Set snap classic
#  ansible.builtin.file:
#    dest: "/snap"
#    src: "/var/lib/snapd/snap"
#    state: link
#  become: yes
