---
- name: Add keyring
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  become: true

- name: Add repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    update_cache: true
  become: true

- name: Install
  ansible.builtin.apt:
    name:
      - kubectl
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.kube/conf.d"
    state: directory

- name: Copy configs
  copy:
    dest: "{{ ansible_user_dir }}/.kube/conf.d/{{ kubectl_config_item.key }}.conf"
    content: "{{ kubectl_config_item.value }}"
    mode: 0600
  no_log: true
  loop_control:
    loop_var: kubectl_config_item
  with_items: "{{ kubectl_config | default({}) | dict2items }}"

- name: Set active
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.kube/config"
    src: "{{ ansible_user_dir }}/.kube/conf.d/{{ kubectl_config_active }}.conf"
    state: link
  no_log: true
  when: kubectl_config[kubectl_config_active] is defined
