---
- name: Download Installer
  ansible.builtin.get_url:
    dest: "{{ ansible_user_dir }}/kitty_installer.sh"
    mode: "0755"
    url: https://sw.kovidgoyal.net/kitty/installer.sh

- name: Install
  ansible.builtin.shell:
    cmd: "{{ ansible_user_dir }}/kitty_installer.sh launch=n"

- name: Create link
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin/kitty"
    src: "{{ ansible_user_dir }}/.local/kitty.app/bin/kitty"
    state: link

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory

- name: Configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
    src: "kitty.conf.j2"

- name: Themes
  copy:
    dest: "{{ ansible_user_dir }}/.config/kitty"
    src: "{{ kitty_config_item }}"
  loop_control:
    loop_var: kitty_config_item
  with_fileglob:
    - "kitty_*"
