---
- name: Create config folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/dunst"
    state: directory

- name: Download theme
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/dunst/dunstrc"
    src: "dunstrc.j2"
