---
- name: Download Installer
  ansible.builtin.get_url:
    dest: "{{ ansible_user_dir }}/tfswitch-installer.sh"
    mode: 0755
    url: https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh

- name: Install
  ansible.builtin.shell:
    cmd: "{{ ansible_user_dir }}/tfswitch-installer.sh"
  become: true
