---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - zlib1g
      - zlib1g-dev
      - libssl-dev
      - libbz2-dev
      - libsqlite3-dev
      - build-essential
      - libreadline-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
  become: true

- name: Check Installation
  stat:
    path: "{{ ansible_user_dir }}/.pyenv"
  register: install

- name: Download Installer
  ansible.builtin.get_url:
    dest: "{{ ansible_user_dir }}/pyenv_installer.run"
    url: https://pyenv.run
    mode: "0755"
  when: not install.stat.exists

- name: Install
  ansible.builtin.shell:
    cmd: "{{ ansible_user_dir }}/pyenv_installer.run"
  when: not install.stat.exists

- name: Cleanup
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/pyenv_installer.run"
    state: absent
  when: not install.stat.exists

- name: Clone pyenv-virtualenv
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.pyenv/plugins/pyenv-virtualenv"
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    update: yes
    version: master

