---
- name: Install Add-ons
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
  become: true

- name: Add keyring
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
  become: true

- name: Add repo
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: true
  become: true

- name: Install
  ansible.builtin.apt:
    name:
      - docker
      - docker-compose
  become: true

- name: Enable service
  ansible.builtin.systemd:
    enabled: yes
    name: docker
    state: started
  become: true

- name: Add to group
  ansible.builtin.user:
    append: yes
    groups: docker
    name: "{{ ansible_env['USER'] }}"
  become: true

- name: Copy daemon.json
  ansible.builtin.template:
    dest: "/etc/docker/daemon.json"
    src: "daemon.json"
  become: true
  notify: restart_docker
